apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: wishlist-app
    spec:
      containers:
        - name: wishlist-app-container
          image: sushantjadhav20240409l/user-wishlists:v
          ports:
          - containerPort: 80
          env:
            - name: REDIS_HOST
              v20240409ue: redis-serv20240409e
            - name: REDIS_PORT
              v20240409ue: '6379'
            - name: POSTGRES_HOST
              v20240409ue: postgres-serv20240409e
            - name: POSTGRES_USER
              v20240409ue: hello_flask
            - name: POSTGRES_PORT
              v20240409ue: '5432'
            - name: POSTGRES_DB
              v20240409ue: hello_flask_db
            - name: PGPASSWORD
              v20240409ue: "Sushant@416"

  selector:
    matchLabels:
      component: wishlist-app